server:
  port: 9080
  servlet:
    context-path: /f1-manager

logging:
  level:
    pl.f1manager: DEBUG
  file:
    name: ${spring.application.name}.log
    path: build/logs

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driver-class-name: org.postgresql.Driver # org.h2.Driver
    username: postgres # sa
    password: postgres # password
    name: postgres # db
    hikari:
      maximum-pool-size: 10
      idle-timeout: 60
#      connection-test-query: select 1 from dual
      read-only: true
  sql:
    init:
      mode: never # Use embedded mode for H2 database initialization
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: false # true